import Head from "next/head";
import NavigationBar from "../components/NavigationBar";
import fetchPosts from "./api/posts";
import Posts from "../components/Posts";

const callAPI = fetchPosts;

export async function getServerSideProps() {
  // Call the callAPI function
  const data = await callAPI();

  // Pass the data as props to the component
  return { props: { data } };
}

export default function Home(props) {
  const posts = props.data.slice(0, 10);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <NavigationBar />
      <Posts posts={posts} />

    </div>
  );
}
